### ISSUE TITLE
Ошибка при указании неправильного пути для sync

### ISSUE THREAD

**Issue by vakulenkoalex** [vakulenkoalex/runner1c#56]
Указали путь к репозитарию без папки build.
Запускаем sync.
Выдает ошибку.

'''
C:\Git\runner1c\venv\Scripts\python.exe C:/Git/runner1c/runner1c/core.py --debug sync --folder C:\Git\runner1c\runner1c\build --path "C:\Program Files (x86)\1cv8\8.3.12.1714"
2021-03-22 15:43:05,688 - DEBUG -                Core - start
2021-03-22 15:43:05,689 - DEBUG -          CreateBase - run1C "C:\Program Files (x86)\1cv8\8.3.12.1714\bin\1cv8.exe" CREATEINFOBASE "File=C:\Git\temp\tmp6jfs24_0" /Out "C:\Git\temp\tmps22wdi71.txt" /L ru /DumpResult "C:\Git\temp\tmpwnqzlikz.txt"
2021-03-22 15:43:06,689 - DEBUG -          CreateBase - result run1C = 0
2021-03-22 15:43:06,691 - DEBUG -          CreateBase - result from a file = 0
2021-03-22 15:43:06,691 - DEBUG -          CreateBase - exit code = 0
Traceback (most recent call last):
  File "C:/Git/runner1c/runner1c/core.py", line 83, in <module>
    sys.exit(main())
  File "C:/Git/runner1c/runner1c/core.py", line 75, in main
    return_code = handler.execute()
  File "C:\Git\runner1c\runner1c\command.py", line 39, in wrapper
    return_code = self.execute()
  File "C:\Git\runner1c\runner1c\command.py", line 28, in wrapper
    return func(self)
  File "C:\Git\runner1c\runner1c\commands\sync.py", line 96, in execute
    self._save_file_hash()
  File "C:\Git\runner1c\runner1c\commands\sync.py", line 119, in _save_file_hash
    with open(self._hash_file_name, mode='w', encoding='utf-8') as file_stream:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Git\\runner1c\\runner1c\\build\\build\\hash.txt'

Process finished with exit code 1

**Comment by vakulenkoalex** [comment]
#59
